# Generated by Django 5.2.8 on 2025-11-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Notificación', max_length=200),
        ),
    ]
