# Generated by Django 5.2.8 on 2025-11-07 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0002_architect_certificate_number_architect_is_certified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationreview',
            name='council_member_status',
        ),
        migrations.RemoveField(
            model_name='applicationreview',
            name='guarantor_1_status',
        ),
        migrations.RemoveField(
            model_name='applicationreview',
            name='guarantor_2_status',
        ),
        migrations.RemoveField(
            model_name='applicationreview',
            name='overall_status',
        ),
        migrations.RemoveField(
            model_name='applicationreview',
            name='supervising_architect_status',
        ),
        migrations.AddField(
            model_name='applicationreview',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicationreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationreview',
            name='reviewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='applicationreview',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20),
        ),
    ]
