# Generated by Django 5.2.8 on 2025-11-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0003_remove_applicationreview_council_member_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='status',
            field=models.CharField(choices=[('review', 'En revisión'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('pending_payment', 'Pendiente de pago'), ('certified', 'Certificado')], default='review', max_length=20),
        ),
    ]
