# Generated by Django 5.2.8 on 2025-11-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architects', '0004_alter_architect_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='architect',
            name='certification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
